### ISSUE TITLE
Are you planning to support Meteor 9.0 

### ISSUE THREAD

**Issue by isAlmogK** [tmeasday/meteor-gravatar#7]
Are you planning to support Meteor 9.0

**Comment by tmeasday** [comment]
Hey @almogdesign - I'm not using this package anywhere at the moment so would happily hand it over to someone else if they want to maintain it. There's not a lot to it.

**Comment by isAlmogK** [comment]
The package is working fine but would be glad to contribute add me as an admin

**Comment by tmeasday** [comment]
Hey @almogdesign no worries -- what's your username?

**Comment by isAlmogK** [comment]
@tmeasday username is almogdesign

**Comment by tmeasday** [comment]
Is that your Meteor Developer username? I'm getting an error when I try to add you

**Comment by isAlmogK** [comment]
No github it's almog for the meteor accounts

**Comment by tmeasday** [comment]
Done.

**Comment by p-j** [comment]
@almogdesign @tmeasday 
FYI: I've published a working version : https://atmospherejs.com/jparker/gravatar

**Comment by tmeasday** [comment]
Good stuff
